### ISSUE TITLE
Questions about Senquential Volumetric Interpolation

### ISSUE THREAD

**Issue by cyiheng** [guoyu-niubility/SVIN#5]
Hi there,

1. Load netG-epoch500-all
To be able to use the Interpolation, do we have to run the Motion Field Estimation first and then use the saved netG-epochXXX ?
Or is it possible to run the interpolation from scratch without any pretrained generator from the motion field ?

Because actually I have tried to use the netG-epoch from the motion field but I have a mismatch error.
```
# STM_Net_Dir = 'netG-epoch500-all'
STM_Net_Dir = './../motion-net/save_motion/netG-epoch400'
```
Error :
```
Traceback (most recent call last):
  File "train_4d.py", line 72, in <module>
    STM_Net.load_state_dict(tmp)
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.up_block6.convb.convs.0.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 56, 3, 3, 3]).
```
Maybe I misunderstand this part and it doesn't mean to load this weight.

2. Skip loading

I have tried to bypass this loading option by commenting these line:
```
    STM_Net = Net_3d_ALL()
    STM_Net.to(device)
    STM_Net = torch.nn.DataParallel(STM_Net, [0])
    # tmp = torch.load(STM_Net_Dir)
    # STM_Net.load_state_dict(tmp)
    # STM_Net.eval()
```
But therefore I meet this error 
```
Traceback (most recent call last):
  File "train_4d.py", line 174, in <module>
    model.optimize_parameters()
  File "/home/yiheng/bacasable/SVIN/interpolation/models/model.py", line 261, in optimize_parameters
    self.forward()
  File "/home/yiheng/bacasable/SVIN/interpolation/models/model.py", line 174, in forward
    self.netG(self.combined_image, self.D96_combine, self.D48_combine, self.D24_combine)
AttributeError: InterpolationModel instance has no attribute 'D48_combine'
```
And in fact, ```self.D48_combine``` as well for ```self.D24_combine``` don't appear in the model.py file.
```
    def set_input(self, combined_image, img0_96, img0_48, img0_24, \
        img1_96, img1_48, img1_24, imgt_96, imgt_48, imgt_24, D0t_96, D1t_96, index_l):

        self.real96_A = imgt_96.to(self.device)
        self.real48_A = imgt_48.to(self.device)
        self.real24_A = imgt_24.to(self.device)
        self.combined_image = combined_image.to(self.device)
        self.img0_96 = img0_96.to(self.device)
        self.img1_96 = img1_96.to(self.device)
        self.img0_48 = img0_48.to(self.device)
        self.img1_48 = img1_48.to(self.device)
        self.img0_24 = img0_24.to(self.device)
        self.img1_24 = img1_24.to(self.device)
        self.D0t_96 = D0t_96.to(self.device)
        self.D1t_96 = D1t_96.to(self.device)
        self.D96_combine = torch.cat([self.D0t_96, self.D1t_96], 1)
        self.index_l = index_l.to(self.device)
```

Thank you in advance

**Comment by yyguo0536** [comment]
Hi, we have to get the motion field firstly, cause the interpolation is based on the deformation.

Please try the latest code version.

**Comment by cyiheng** [comment]
Thank you for your update !

So I had these issues that I think I fixed: 
**Missing ``` NetJustUpBlock```**
```
Traceback (most recent call last):
  File "train_4d.py", line 68, in <module>
    STM_Net = Net_3d_ALL()
  File "/home/yiheng/bacasable/SVIN/interpolation/motion_model.py", line 155, in __init__
    self.up_block6 = NetJustUpBlock(80, 32, 2)#96
NameError: global name 'NetJustUpBlock' is not defined
```
I went to the "net_3d.py" of the motion-net folder and copy/paste the ``` NetJustUpBlock ``` .

**Variable undefined**
```
Traceback (most recent call last):
  File "train_4d.py", line 162, in <module>
    tD10_48, D10_48[:,0,:,:,:], D10_48[:,2,:,:,:], D10_48[:,1,:,:,:])
NameError: name 'tD10_48' is not defined
```
I just took out the ' t ' before ```D10_48```  as well as for ```tD10_96``` and ```tD10_24``` 

**Shape error in ```NetInBlock ```**
``` 
Traceback (most recent call last):
  File "train_4d.py", line 144, in <module>
    combined01_96, combined10_96)
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yiheng/bacasable/SVIN/interpolation/motion_model.py", line 212, in forward
    field12_24, field12_48, field12_96 = self.forward_branch(combined12)
  File "/home/yiheng/bacasable/SVIN/interpolation/motion_model.py", line 184, in forward_branch
    br1 = self.in_block(combined_image)
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yiheng/bacasable/SVIN/interpolation/motion_model.py", line 53, in forward
    out = torch.add(out, x)
RuntimeError: The size of tensor a (24) must match the size of tensor b (2) at non-singleton dimension 1
```
I comment the line with ```out = torch.add(out, x)``` like in the ```net_3d.py```.

**Then I got another shape error in ```interpolation.py ```**
```
Traceback (most recent call last):
  File "train_4d.py", line 206, in <module>
    model.optimize_parameters()
  File "/home/yiheng/bacasable/SVIN/interpolation/models/model.py", line 271, in optimize_parameters
    self.forward()
  File "/home/yiheng/bacasable/SVIN/interpolation/models/model.py", line 184, in forward
    self.netG(self.combined_image, self.D96_combine, self.D48_combine, self.D24_combine)
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yiheng/anaconda3/envs/svin/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yiheng/bacasable/SVIN/interpolation/models/interpolation.py", line 243, in forward
    df_fc24 = self.down_24_1(deform24[:,:-1,:,:,:]-combined_def24)
RuntimeError: The size of tensor a (24) must match the size of tensor b (96) at non-singleton dimension 4
```
So I went back to your update in ```model.py``` and correct this : 
```
        self.D0t_24 = D0t_96.to(self.device)
        self.D1t_24 = D1t_96.to(self.device)
        self.D24_combine = torch.cat([self.D0t_24, self.D1t_24], 1)
```
to
```
        self.D0t_24 = D0t_24.to(self.device)
        self.D1t_24 = D1t_24.to(self.device)
        self.D24_combine = torch.cat([self.D0t_24, self.D1t_24], 1)
```
